# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - hello-world649

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: https://hello-world649.azurewebsites.net/
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hello-world649'
          slot-name: 'Production'
          publish-profile: <publishData><publishProfile profileName="hello-world649 - Web Deploy" publishMethod="MSDeploy" publishUrl="hello-world649.scm.azurewebsites.net:443" msdeploySite="hello-world649" userName="$hello-world649" userPWD="brLAbqJbmreevyvsMGzX0yr1F9BTs3pL2S0YGxlau1WBPyZiiJkkvo0Zv1D1" destinationAppUrl="https://hello-world649.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="hello-world649 - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-435.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="hello-world649\$hello-world649" userPWD="brLAbqJbmreevyvsMGzX0yr1F9BTs3pL2S0YGxlau1WBPyZiiJkkvo0Zv1D1" destinationAppUrl="https://hello-world649.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="hello-world649 - Zip Deploy" publishMethod="ZipDeploy" publishUrl="hello-world649.scm.azurewebsites.net:443" userName="$hello-world649" userPWD="brLAbqJbmreevyvsMGzX0yr1F9BTs3pL2S0YGxlau1WBPyZiiJkkvo0Zv1D1" destinationAppUrl="https://hello-world649.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          package: '*.war'
